repository:
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
collaborators:
  - username: travi-bot
    permission: push
labels:
  - name: bug
    color: ee0701
    description: Something isn't working
  - name: duplicate
    color: cccccc
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: breaking change
    color: e0fc28
    description: This change would break the current public interface for consumers
  - name: greenkeeper
    color: 00c775
    description: This was opened by the Greenkeeper service
  - name: semantic-release
    color: ededed
    description: This was opened by semantic-release
  - name: released
    description: This issue or pull-request was included in a version released by semantic-release
